### ISSUE TITLE
uploader.submit() does not error if not file is selected.

### ISSUE THREAD

**Issue by mouse0270** [LPology/Simple-Ajax-Uploader#101]
I have a form where if the user does not select a file I will default it to a standard image. The problem is I would like to check this after a file has been uploaded.

But if I call `uploader.submit()` and there was no file selected there is no type of error throw. How do I tell that `uploader` failed to upload because no image was selected.

**Comment by LPology** [comment]
Sorry for such a long delay in replying to this.

Version 2.4 of the plugin includes a new callback function called `onBlankSubmit()` which gets called when a user attempts to submit without selecting a file.

Thanks for your input.
