### ISSUE TITLE
Invisible button still present when upload button moves

### ISSUE THREAD

**Issue by waveint** [LPology/Simple-Ajax-Uploader#105]
Firstly - Brilliant plugin.

However we have a slight issue. When we add dynamic fields to our form it appears an invisible button remains where the button was?

Any ideas?

**Comment by vovayatsyuk** [comment]
Hi,

I didn't found any public methods for this purpose.

But, you can manually update invisible button position:

```js
ss.copyLayout(document.getElementById('upload-btn'), uploader._input.parentNode);
```
