### ISSUE TITLE
Querystring are followed after url while post method

### ISSUE THREAD

**Issue by yjk891** [LPology/Simple-Ajax-Uploader#109]
I set up "Var uploader" instantiated by ss.SimpleUpload.
Also method is 'post'.

When i tracked down request path by google developers, queryString is right after url. 
By any chance, is there any option not to put query string after request url?

**Comment by LPology** [comment]
I know this is an old question, but the answer is just to set `noParams: true ` in your Javascript settings. By default, it's `false`, which adds query string params to the URL.
