### ISSUE TITLE
How exactly to use setData()

### ISSUE THREAD

**Issue by jeebsion** [LPology/Simple-Ajax-Uploader#111]
Everything went well as per example until I realize that I need to pass additional variable to upload.php. Any advice, please?

**Comment by LPology** [comment]
The most common way is to use it in the `onSubmit()` callback function:

```javascript
onSubmit: function() {
    var self = this;

    self.setData({
        someItem: 'value of first item',
        anotherItem: 'value of second item'
    });
});
```

You'll then be able to access the data on the server side as you normally would a file input. You mentioned PHP:

```php
$someItem = $_REQUEST['someItem']; // 'value of first item'
$anotherItem = $_REQUEST['anotherItem']; // 'value of second item'
```
