### ISSUE TITLE
Can't get the given example to work

### ISSUE THREAD

**Issue by mat-duf** [LPology/Simple-Ajax-Uploader#113]
A the title says, I can't get the given example to work (it seems I am not the only one).
Here is the server response through debug mode :
"[Uploader] Server response: <br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
{"success":false,"msg":"Upload directory is not writable"}"1 SimpleAjaxUploader.js:633:13

I hope anyone know a fix/workaround.

**Comment by LPology** [comment]
The message "Upload directory is not writable" means your upload directory either does not exist, or does not have correct permissions set.
