### ISSUE TITLE
onChange 3rd parameter , how to use button reference 

### ISSUE THREAD

**Issue by darkworks** [LPology/Simple-Ajax-Uploader#114]
i wish onChange function could return button id  or can you explain how to use this 3rd parameter of it , i mean docs say it return button reference , so how to use that reference if i have to change that button text  .
for example upload button clicked file selected by user , onChange function called now how can i change button text 

http://stackoverflow.com/questions/31570909/how-to-use-button-reference-in-jquery/31571621#31571621

onChange( filename, extension, uploadBtn )

**Comment by zaygraveyard** [comment]
This is a bug, it's not your fault. Please see #115 for a proposed fix.

**Comment by LPology** [comment]
@darkworks Thanks for for your input here.

@zaygraveyard Thanks for submitting a fix. It has been merged.
