### ISSUE TITLE
Cannot get the example to work

### ISSUE THREAD

**Issue by ch1n3s3b0y** [LPology/Simple-Ajax-Uploader#117]
Hi

I'm on Windows 8 using XAMPP. I have tried this on one of my own pages and also I have tried the example and neither work. The page loads fine. All of the scripts seem to be loading fine, but whenever I upload a file I just get the error 'Unable to upload file'.

Any idea where I am going wrong?

**Comment by LPology** [comment]
Set the `debug` option to `true` in your JS configuration. This will report errors into the console. Can you do that and tell me what it says?

**Comment by ch1n3s3b0y** [comment]
[Uploader] Server response: <br />
<b>Warning</b>:  require(/Simple-Ajax-Uploader-master/extras/Uploader.php): failed to open stream: No such file or directory in <b>C:\xampp\example\Simple-Ajax-Uploader-master\examples\basic_example\file_upload.php</b> on line <b>2</b><br />
<br />
<b>Fatal error</b>:  require(): Failed opening required '/Simple-Ajax-Uploader-master/extras/Uploader.php' (include_path='.;C:\xampp\php\PEAR') in <b>C:\xampp\example\Simple-Ajax-Uploader-master\examples\basic_example\file_upload.php</b> on line <b>2</b><br />

I think I see the problem...

**Comment by ch1n3s3b0y** [comment]
I change the require path to:

$root = realpath($_SERVER["DOCUMENT_ROOT"]);
require($root.'/Simple-Ajax-Uploader-master/extras/Uploader.php');

Now I'm getting the error

'Upload directory is not writable'

I'm on windows 8, XAMPP. I would think the directory is writeable.

**Comment by ch1n3s3b0y** [comment]
Got it working!

**Comment by LPology** [comment]
Excellent! Glad to hear it. I'll go ahead and close this one out.
