### ISSUE TITLE
Upload multiple files using multipart: true

### ISSUE THREAD

**Issue by Thilaga14** [LPology/Simple-Ajax-Uploader#123]
how to upload multiple files using multipar:true. 

anyexamples?

**Comment by LPology** [comment]
It's the same as the example in the README. What problem are you having?

**Comment by Thilaga14** [comment]
I need something like below. multiple:true and multipart:true. I can able to select multiple files but it is not sending those to server. 

 var myUploader = new ss.SimpleUpload({
	        button: btn,
	        url: 'uploadServlet',
	        name: 'uploadfile',
	        multipart: true,
	        multiple:true,
	        hoverClass: 'hover',
	        focusClass: 'focus',
	        noParams:true,
	        autoSubmit:false,
	        responseType: 'json',
	        debug:true,
	        onComplete: function( filename, response ) {
	        	console.log('onComplete');	        	
	          },
	        onError: function(filename, errorType, status) {	        	
	        	console.log('onError');	        	
	          }
		});

**Comment by LPology** [comment]
None of the files are being sent to the server at all?

**Comment by LPology** [comment]
Can you explain exactly what is happening when you try to upload a file?

Also, set `debug: true` in your settings and let me know what it says your browser console.

**Comment by Thilaga14** [comment]
1. I can able to select multiple files(for ex : 3)  in file browser and click open 
2. But in ajax call, I can see 14 params in Request payload in that 13 are data params and 1 is file (only one file is going instead of 3)

In console : 

[Uploader] Commencing upload using multipart form
[Uploader] Server response: {"Audit_ID" : "21"}

**Comment by LPology** [comment]
That is actually how the plugin works -- it only sends one file per request. The reason is to support multiple, concurrent file uploads in IE7-9. When multiple files are being uploaded, each file upload is a separate request.

**Comment by Thilaga14** [comment]
It is not even sending multiple request. It is sending one request and one file. You can prevent using both multipart:true and multiple: true at the same time. 

Thanks !

**Comment by LPology** [comment]
What browser are you using?

**Comment by Thilaga14** [comment]
Chrome

**Comment by LPology** [comment]
I'm not sure what the issue could be. It doesn't seem like there should be any reason why you are only having one request when you select more than one file. 

Is there a way you can post a link to a live example? If you can't do that, can you post or link to the full code?

**Comment by Thilaga14** [comment]
my code is in reactJS

```javascript

    initUpload:function(props){
    var self = this; 
    
    	var btn = document.getElementById('uploadBtn'),
	      progressBar = document.getElementById('progressBar'),
	      progressOuter = document.getElementById('progressOuter'),
	      msgBox = document.getElementById('msgBox');
	
	 	 var myUploader = new ss.SimpleUpload({
	        button: btn,
	        url: 'uploadServlet',
	        name: 'uploadfile',
	        multipart: true,
	        multiple:true,
	        hoverClass: 'hover',
	        focusClass: 'focus',
	        noParams:true,
	        autoSubmit:false,
	        responseType: 'json',
	        debug:true,
	        onSubmit: function() {			    
	        	self.setState({msgBox : '',uploadBtn:'Uploading...'});
	          },
	        onChange:function(filename){
	        	self.setState({msgBox : filename, isFileSelected:true})
	        },
	        onComplete: function( filename, response ) {
	        	console.log('onComplete');
	        	console.log(filename);
	        	console.log(response);
	        	self.setState({ uploadBtn: 'Choose Another File'});
	
	            if ( !response ) {
	            	self.setState({ msgBox: 'Upload failed'});
	                return;
	            }
	            
	            props.onCommentSubmit(props.action, self.state.comment, response.Audit_ID);
	    		self.hide();
	
	         /*    if ( response.success === true ) {
	            	self.setState({ msgBox: escapeTags( filename ) + '</strong>' + ' successfully uploaded.'});
	
	            } else {
	                if ( response.msg )  {
	                	self.setState({ msgBox: escapeTags( response.msg )});
	
	                } else {
	                self.setState({ msgBox: 'An error occurred and the upload failed.'});
	                }
	            } */
	          },
	        onError: function(filename, errorType, status) {
	        	
	        	console.log('onError');
	        	console.log(filename);
	        	console.log(errorType);
	        	console.log(status);
	           self.setState({ uploadBtn: 'Choose Another File'});
	           self.setState({ msgBox: 'Unable to upload file'});
	          }
		});
		
		this.setState({myUploader:myUploader});
    },


     onClickSubmit: function(e) {

     	var self = this;
	    e.preventDefault();
      	console.info("coment"+this.refs.comment);
	    var comment = React.findDOMNode(this.refs.comment).value.trim();
	    if (!comment) {
	     alert('enter comment');
	      return;
	    }
	    
	    var data = self.props.data;
	   data.comments = comment;
	   
	   console.log(data);
	   
	   self.setState({comment:comment});
	   
	   if(self.state.isFileSelected)
	   {		   		
	  	 console.log(' an file upload');    
		   self.state.myUploader.setOptions({
		    	data : data
		    });
		    self.state.myUploader.submit();
		}
		else
		{		
			console.log('not an file upload');
			$.ajax({
		      url: 'uploadServlet',
		      dataType: 'json',
		      type: 'POST',
		      data: data,
		      success: function(response) {
		        self.props.onCommentSubmit(self.props.action, self.state.comment, response.Audit_ID);
		        self.hide();
		      }.bind(this),
		      error: function(xhr, status, err) {
		        alert(err);
		      }.bind(this)
		    });
			
			self.hide();
		}
	  },

```

**Comment by LPology** [comment]
Is the one file that is being sent successfully uploading?

**Comment by Thilaga14** [comment]
yes. I can read and store

**Comment by LPology** [comment]
I think I've figured it out. I think it's because you have `autoSubmit: false` and when you submit the upload here:

```javascript
self.state.myUploader.submit();
```

It's only submitting the first file because when `autoSubmit` is `false`, the plugin does not automatically submit the next file. You could do something like this:

```javascript
if(self.state.isFileSelected)
       {                
         console.log(' an file upload');    
           self.state.myUploader.setOptions({
                data : data
            });
            var num = self.state.myUploader.getQueueSize();
             for ( var i = 0, len = num.length; i < num; i++ ) {
                  self.state.myUploader.submit();
              }
            
        }
```

This finds how many files were selected using `getQueueSize()` and then submits each file individually.

Can you try this and see if it works?

**Comment by Thilaga14** [comment]
Yup! you solved it . Thanks :). I can see multiple request with one file at a time. 

Last question for better understanding, 

Chrome - select n files and send n requests, one file at time. 
IE7-9 - not able to select multiple files as browser is not supporting 
IE10+ - works like chrome. 

is anything possible like one request with multiple files ? 

correct me if i am wrong.

**Comment by LPology** [comment]
Glad I could help. You're correct about the browsers.

One request with multiple files might be possible. I'd have to work on it, but it could potentially be in a future release. I'll look into it.

**Comment by Thilaga14** [comment]
Resolved..
