### ISSUE TITLE
Slow file uploading

### ISSUE THREAD

**Issue by bologer** [LPology/Simple-Ajax-Uploader#127]
Hello, 

I am using this Simple-Ajax-Uploader and I recently find out that it is pretty slow on file larger files (1.2-x.x mb). I am not sure if it is because of the plugin or it is because of the server. 

Could you please give me some clue about this issue?

**Comment by LPology** [comment]
Is it slow during the actual upload, or somewhere else? If it's slow during the upload, it's almost certainly a networking or server issue. Have you done any other benchmarking?

**Comment by bologer** [comment]
Alright. What about server-side part of this script? Does it work fast on large files? And if everything is OK with the script and it is problem with the server, could you please suggest some improvement for the back-end part?
