### ISSUE TITLE
UploadHandler.php

### ISSUE THREAD

**Issue by Urihorsemouth** [LPology/Simple-Ajax-Uploader#130]
Hello! I am trying to set up the simple-ajax-uploader and let me tell you, the title is misleading to say the least. Where is the UploadHandler.php file? Did you rename it to file_upload.php?? The example is not working on any of my servers and setups. Can you help with some guidelines, i read the documentation and did the suggested...i tried to set up the basic example files and no luck... 

I'm stuck...when i click a button on my index.html page nothing happens and i think that i have correctly set up the folders and scripts.

Please help!

Have a nice day, Uroš

**Comment by LPology** [comment]
Take a look at the example in the examples folder. That should get you started in the right direction.
