### ISSUE TITLE
Problem with uploaders created on elements in bootstrap accordion

### ISSUE THREAD

**Issue by sergey-suloev** [LPology/Simple-Ajax-Uploader#135]
I have a problem with uploaders created on elements in bootstrap accordion. Accordion's panels are initially collapsed and  elements are hidden. This causes SimpleUpload to create absolutely positioned elements with incorrect coordinates. When accordion panels are expanded then a file input and its parent may overlap wrong elements
Ways to fix that ?

**Comment by LPology** [comment]
Can you post or link to an example?

**Comment by LPology** [comment]
I believe I have found a fix. Can you try give this a try and let me know how it goes?

http://pastebin.com/raw/vxaJ9ya2

If that solves it I'll push an update with the fix.
