### ISSUE TITLE
v2.4 file uploads are zero length

### ISSUE THREAD

**Issue by dleffler** [LPology/Simple-Ajax-Uploader#137]
I've been using this product for several years, but after moving from v2.3 to v2.4 it seems to have broken something.  This upload is handled within php as an XHR but the 
    file_put_contents($_destFullPath, file_get_contents('php://input'));
only creates a zero-length file with no errors reported.  Reverting back to the v2.3 file restores functionality.

**Comment by LPology** [comment]
In your Javascript code, set this option for the uploader: `multipart: false`

**Comment by dleffler** [comment]
I've tried that, but then it doesn't send back any parameters in $_REQUEST ('data' parameter), nor is the name or filename sent

**Comment by LPology** [comment]
Try setting `noParams: false`

**Comment by dleffler** [comment]
That seems to have done the trick, required explicitly setting both (back) to false.  Thanks!

**Comment by LPology** [comment]
Glad to help. 

And sorry for the annoyance. The reason for the change is that I think it will make it easier for people to use the plugin going forward by defaulting to the more broadly accepted method of uploading files (multipart form). 

I'll update the Changelog with a little more detail. Let's also leave this issue open for a little while to make it easier to find in case anyone else comes across the same problem. Thanks for bringing it up.
