### ISSUE TITLE
[bug]duplicate file param  when submit as  multipart

### ISSUE THREAD

**Issue by djxhero** [LPology/Simple-Ajax-Uploader#141]
fileName pass twice when submit as multipart; I don't know whether it is a bug or not

the first name param just only the custom file name param I named it,
and the second is custom   file name  param and real filename ;

and this not work with my server side program，so I remove the first fileName param.

### --------------original param pass  like :-------------
```
------WebKitFormBoundaryOji6kqweUHAmIGy9
Content-Disposition: form-data; name="routeFile"   <---- (this should be remove)

a.txt
------WebKitFormBoundaryOji6kqweUHAmIGy9
Content-Disposition: form-data; name="routeFile"; filename="a.txt"
Content-Type: text/plain

------WebKitFormBoundaryOji6kqweUHAmIGy9--
```

###  -----I remove the first file name param , and this work for me-
```
------WebKitFormBoundaryvkRf5Xz9Ejap9BIY
Content-Disposition: form-data; name="routeFile"; filename="a.txt"
Content-Type: text/plain


------WebKitFormBoundaryvkRf5Xz9Ejap9BIY--

```

**Comment by LPology** [comment]
Which version of the plugin are you using?

**Comment by djxhero** [comment]
Simple Ajax Uploader v2.4

**Comment by ablipan** [comment]
I met the problem either with the latest version 2.4.0.
Setting the name option with 'file' , there will be two 'file' in the form-data.
```
------WebKitFormBoundaryys9VdMimwU0Aeiux
Content-Disposition: form-data; name="file"
user/image/296/J99BXJv35iIAQlTrqSbmiJOR6L8Zc8Kj_1453565318410.jpg
------WebKitFormBoundaryys9VdMimwU0Aeiux
Content-Disposition: form-data; name="file"; filename="10.jpg"
Content-Type: image/jpeg
```
@djxhero +1  Remove that line is working for me.
@LPology Maybe it is a bug ?

**Comment by LPology** [comment]
@ablipan  @djxhero This is a good catch. Just pushed an update (version 2.5.0) that removes this line. 

Thanks for your input.
