### ISSUE TITLE
input can't lay on fixed position element 

### ISSUE THREAD

**Issue by suhaotian** [LPology/Simple-Ajax-Uploader#163]

**Comment by suhaotian** [comment]
maybe give a option to set position to fixed or absolute ?

**Comment by LPology** [comment]
I'm not sure I understand the issue. What problem is being created?

**Comment by suhaotian** [comment]
@LPology I have a button on fixed position, like:
```html
    <div class="container" style="position: fixed;bottom: 20px;right: 20px;">
        <button id="upload-btn">upload file</button>
    </div>
```
```js
new ss.SimpleUpload({
  button: document.getElementById('upload-btn'),
  ...
})
```
click the button, but can't select file to upload.

**Comment by suhaotian** [comment]
I'm sorry, just now I test DOM with fixed style, It work. Thank for your patient 😄
