### ISSUE TITLE
Include a multiple upload example?

### ISSUE THREAD

**Issue by slambert** [LPology/Simple-Ajax-Uploader#193]
I'm able to get the basic example up an running. When I try to change it for multiple upload, I can't seem to get the results I'm hoping for. Could a multiple upload example be added?

**Comment by LPology** [comment]
What results are you not getting that you expect?

**Comment by slambert** [comment]
Right now I can only upload 1 file at a time - can't select more than one

I think I kept the html file pretty close to the same as in the example, but I know I made these changes:

          multiple: true,
          multipart: true,
          maxUploads: 10,
          autoSubmit: true,

**Comment by samgre** [comment]
We're experiencing the same issue. Multiple file uploads worked with v2.5.5, but not with v2.6.2.

Here's our config:

                'button': this.$el,
                'url': this.uploadRoot,
                'allowedExtensions': ['gif', 'jpeg', 'jpg', 'png'],
                'hoverClass': 'ui-state-hover',
                'focusClass': 'ui-state-focus',
                'multiple': true,
                'name': 'image',
                'customHeaders': {'X-CSRFToken': 'TOKEN'},
                'onSubmit': this.onUploadSubmit,
                'onError': this.onUploadError,
                'onComplete': this.onUploadComplete

**Comment by bondydaa** [comment]
We are using v2.6.2 as well and it seems that `maxUploads` has no effect to allow a user to select more than 1 file. 

Using Chrome Version 60.0.3112.113 (Official Build) (64-bit), OSX Sierra 10.12.6 (16G29)

**Comment by LPology** [comment]
There was a change in the 2.6 release which added a new option `multipleSelect` to allow/disallow multiple file selection. Set `multipleSelect` to `true`  in your plugin settings to enable multi file selection.

Check out the Version 2.6 release notes here:

https://github.com/LPology/Simple-Ajax-Uploader/blob/master/Changelog.md
