### ISSUE TITLE
Upload to NPM

### ISSUE THREAD

**Issue by soofka** [LPology/Simple-Ajax-Uploader#220]
Hello,

Are you going to upload new versions of this package to NPM? Latest version here is 2.6.6, while latest version on NPM is 2.5.5. In my project currently we are downloading newest versions from GitHub manually but it is not very future-proof solution :-).

Best regards,
Jakub

**Comment by LPology** [comment]
I actually do not own the npm package:

https://www.npmjs.com/package/simple-ajax-uploader

However I have pinged the person who owns it, so hopefully I will hear back and will be able to publish to npm.

**Comment by LPology** [comment]
I now own the NPM package and it has been updated to latest version 2.6.6:

https://www.npmjs.com/package/simple-ajax-uploader

Thank you, resolving.

**Comment by soofka** [comment]
Amazing, thank you! For quick response and very quick action :-). Cheers!
