### ISSUE TITLE
Call reaches controller, butI can't get the file on the server side. ASP.NET MVC

### ISSUE THREAD

**Issue by heitorb** [LPology/Simple-Ajax-Uploader#35]
I am trying to make this work with the most basic configuration possible. I get the input dialogue, select the file and it reaches my controller on the server side but the file does not come:

HTML:
&lt;img src="/images/PlaceholderImage_button.png" id="MainImageButton" /&gt;

JS:
var uploader = new ss.SimpleUpload({
            button: 'MainImageButton', // HTML element used as upload button
            url: '/Market/UploadImage', // URL of server-side upload handler
            name: 'newImageFile' // Parameter name of the uploaded file
        });

Server Side ASP.NET MVC Controller:
public ContentResult UploadImage(HttpPostedFileBase newImageFile)

The controller is reached but "newImageFile" is null. As a matter of fact, I've looked into the request object and no file is being sent. I've tried different upload controls and this works as long as the "name" parameter in the file input element matches the argument name in the controller (in this case "newImageFile"). I am trying this one because it works with IE9, but I can't seem to implement it.

Any ideas of what the issue may be?

**Comment by kemalemin** [comment]
Don't know about him but it definitely helped me!
