### ISSUE TITLE
Press enter when focus is on button, doesn't work

### ISSUE THREAD

**Issue by umarfarooq125** [LPology/Simple-Ajax-Uploader#49]
Use tab button to navigate to upload button. Press enter. Nothing happens. 
Fix: It should open upload file popup as normal browse button do.

**Comment by LPology** [comment]
Closing out old issues. Unfortunately this particular issue is not on the roadmap to be fixed in the near future. If you would like to submit a fix for the issue, please feel welcome to do so. Thank you for your input.
