### ISSUE TITLE
uploaded files end up in $_POST rather than $_FILES

### ISSUE THREAD

**Issue by danushk** [LPology/Simple-Ajax-Uploader#56]
first of all Thanks for your awesome plugin ,

But i had this issue with it ,  i am using following code 

			$(document).ready(function(){
				var uploader = new ss.SimpleUpload({
					  button: 'file', // HTML element used as upload button
					  url: '/process-product-images-ajax', // Laravel route which handles upload
					  name: 'file', // Parameter name of the uploaded file
					  onComplete:function(filename,response){
						  console.log(response);
					  }
				});
				
				$('#file').on('change', function(){
				});
			});

this populates only $_POST and not $_FILES ,  is there any workaround to fix this ?

cheers

**Comment by ChrisMiko** [comment]
@schlowmo Thx for your tip, it's work fine, @dannymichel yes you see in controller.
