### ISSUE TITLE
Getting progress bar without nginx/php apc

### ISSUE THREAD

**Issue by sojin** [LPology/Simple-Ajax-Uploader#58]
I've mentioned this in my prev issue, but its closed now, sorry for repeating it here.

Quick qs, is it possible to get the progress working for older browsers by sending some json progress updates(size remaining etc..) from server instead of using nginx/php apc? I'm kind of at the unfortunate side now, won't be able to use or modify nginx conf at the moment.

Thanks in advance

**Comment by LPology** [comment]
This feature has been added.
