### ISSUE TITLE
Empty X-Requested-With Header on server for IE 8 & 9

### ISSUE THREAD

**Issue by nicholasc** [LPology/Simple-Ajax-Uploader#65]
Hi,

Using the following code:
```
var uploadPostImage = new ss.SimpleUpload({
		button: 'fileupload-btn-post-image',
		url: '/posts/upload/image', 
		data: {
			"member_id": member_id 
		},
		name: 'uploadfile',
		hoverClass: 'hover',
		allowedextensions: ['jpg', 'jpeg', 'png', 'gif', 'bmp'],
		responseType: 'json',
		multipart: true
});
```

On my server (CentOS 6, Apache 2, PHP 5.4) the X-REQUESTED-WITH header value is never set. I use a function to check if the request is a valid ajax request and it systematically fails on IE 8 & 9.

**Comment by LPology** [comment]
Uploads in IE8 and 9 use the hidden iframe method, as they do not natively support ajax uploads. As a result, there is no way to send custom headers in IE8 and 9.

**Comment by johnlimpin** [comment]
Any updates if there's a solution to this one?

Thanks

**Comment by nicholasc** [comment]
I doubt that there will ever be one. IE 8 & 9 do not support custom headers so there is no way to accurately know if the request was asynchronous. The work around used here simply sends a request through an iframe simulating the behaviour of an ajax call.
