### ISSUE TITLE
IE 11 disabled behavior

### ISSUE THREAD

**Issue by ssn3398** [LPology/Simple-Ajax-Uploader#70]
The uploader has worked great for us for some time. Really like it. 
We support chrome and more recent versions of IE.

I'm using Version 1.10.1 of the uploader.
Still works great in Chrome but with IE 11, I can consistently reproduce loss of focus or perhaps the uploader is disabled. I am able to mitigate by clicking in a different window and then coming back and clicking on my divWrapAttachPhotoMyComputer div.

When I launch the modal, about 30% of the time the uploader won't activate.
If it does activate, once I've clicked on it, I cancel the file selection and then 100% on IE 11, I'm in this disabled state.
Interestingly, if I go ahead and upload a file, I can then click many times on the div and it all works fine.

I'd appreciate any ideas. Thanks!

My uploader is an element on a modal YAHOO.widget.Panel. I can click on other buttons on the modal so the entire modal isn't loosing focus.

Here's my uploader instantiation.

        this.uploader = new ss.SimpleUpload({
            button: 'divWrapAttachPhotoMyComputer', // HTML element used as upload button
            url: './uploadHandler.ashx', // URL of server-side upload handler
            name: 'uploadedFile', // Parameter name of the uploaded file
            responseType: 'json',
            allowedExtensions: ['jpg', 'jpeg', 'png', 'gif'],
            multipart: false,
            hoverClass: 'hover',
            onComplete: function (filename, response) {
                me.fileUploaded(response, me);
            },
            onExtError: function (filename, ext) {
                if (ext.length == 0) {
                    CMinder.Utility.alertCancel('Your file doesn`t appear to have a file extension. Please append the appropriate file extension to the file name and try again.', $('cmContainer'), 'Invalid File Type');
                } else {
                    CMinder.Utility.alertCancel('Please upload a file of one of the following types: .jpg, .gif, .png', $('cmContainer'), 'Invalid File Type');
                }
            }
        });

**Comment by LPology** [comment]
Closing out old issues. This particular issue should be resolved with recent updates. If not or if the issue arises again, please reopen. Thank you.
