### ISSUE TITLE
Incorrect upload name or no file uploaded

### ISSUE THREAD

**Issue by jasondavis** [LPology/Simple-Ajax-Uploader#72]
I have tried to copy the exact demo page code from the demo for the Frontend and then used the default PHP code that is in the project Repo for the backend, no matter what I change I always get this error in the frontend, it appears to do the upload by showing the progress bar and then shows this error message and does not save any file 

    Incorrect upload name or no file uploaded

I could really use some help, have spent a whole day and my boss is very unhappy and I have no idea what the problem is, it does not trigger any other errors!!!!!!!!

Please help.

Demo can be found here https://www.channelletter.com/channel-wizard/testuploader/index2.html

**Comment by LPology** [comment]
Good call. I've updated Uploader.php to make the default value of `$uploadFile` to be `"uploadfile"` to matches the examples. Thanks for your input.
