### ISSUE TITLE
IE9 causing JSON to download

### ISSUE THREAD

**Issue by mattdesl** [LPology/Simple-Ajax-Uploader#73]
When I try this on IE9 it is treating the result as a download. It pops up as "Do you want to open or save uploadd9021494912.json" instead of continuing the callbacks through JS.

Settings:
```js
			url: ...
			name: 'file',
			method: "POST",
			multipart: true,
			data: {
				...
			},
			responseType: 'json',
			allowedExtensions: ['jpg', 'jpeg', 'png', 'gif'],
			maxSize: 15024, // kilobytes
```

**Comment by ingro** [comment]
Got the same problem too, if I set the response type to `application/json` IE 8 and 9 ask to download a .json file, while if I set the response type to `text/html`, on all the browsers, it triggers both the `onComplete` and `onError` callback :(

Here's the code:

```javascript
uploader = new ss.SimpleUpload({
    button: 'upload-btn',
    url: '/upload_img',
    name: 'img',
    allowedExtensions: ['jpg', 'jpeg', 'png'],
    maxSize: 1024,
    onComplete: function(filename, response) {
        alert(response.message);
    },
    onError: function(filename, errorType, status, statusText, response) {
        alert('Unable to complete the upload process!');
    }
});
```

The result is that I see before the first alert (with undefined content) and then the one inside `onError` callback.

Moreover if I set `responseType: 'json'' in the uploader config, the response is correctly parsed and it yells the right content on the 'onComplete' callback, but it triggers the 'onError' callback anyway :(
