### ISSUE TITLE
How can I set a parent element to insert the "div" element

### ISSUE THREAD

**Issue by ChibiBlasphem** [LPology/Simple-Ajax-Uploader#75]
Hello, thanks for your work on this plug-in. I really like it.

I have some problems. Actually, my button which is set as the plugin button is by default not displayed and only displayed when a hover occurs on the parent element.

This cause the following problem :
When instanciating the plugin for the button, the input is placed just fine.
But when i'm hovering it, due to the fact i'm not in the parent element element of the button, the button disappears.

Is there a way to insert the "div > input[type="file]" in a chosen element ?

Thanks for your answers =)

**Comment by LPology** [comment]
Closing out old issues. Please feel free to reopen if your issue has not been resolved or arises again. Thank you.
