### ISSUE TITLE
How to trigger the submit() function manually?

### ISSUE THREAD

**Issue by WonSoon** [LPology/Simple-Ajax-Uploader#81]
Hello, Tnx for this great tool!

I'd like to use "autoSubmit: false" and trigger manually with the submit() function.
But I can't trigger the submit() function. (I don't know how to trigger the submit() function manually.)
Could you give me the examples for using submit() function?

**Comment by tetshi** [comment]
However, if you set autoSubmit to false, it doesn't build the queue list like it does when it's set to true. 

I was trying to leave autosubmit on, but return false on the onSubmit action so the upload wouldn't start automatically. This way, it still builds the list (shows the files to be uploaded). The issue with this is when you use my_uploader.submit(), it doesn't start the upload, but duplicates the files names in the list for some reason.
