### ISSUE TITLE
How can I read custom data on a server?

### ISSUE THREAD

**Issue by simar88** [LPology/Simple-Ajax-Uploader#87]
I would like to know the correct way to read data passed through the field data.
Assuming that i set it to: 
<b>data:{"test":"1"}</b>
I think to read it in this way on php server:
<b>var test = $_POST["test"];</b>
but nothing is inside it. Where i'm doing wrong?
Thanks in advance.

**Comment by LPology** [comment]
Try this:

`var test = $_REQUEST["test"];`

**Comment by venuslikestolearn** [comment]
thanks for the tip. But how one can transfer the dynamic data to the server. How can I send an value chosen from the dropdown list along with the file:

data: {"test": $("#testValue").val()}
