### ISSUE TITLE
customHeaders are encoded

### ISSUE THREAD

**Issue by JohnMcAvinue** [LPology/Simple-Ajax-Uploader#93]
I'm using Bearer authentication and need to pass an authorisation token in the header in the format "Bearer AuthTokenValue".

I'm setting the customHeaders like this:

customHeaders: { "Authorization": "Bearer " + self.Parent().accessToken() },

This results in the following being sent:

Bearer%205MZVwIi9E3-J

It should be:

Bearer 5MZVwIi9E3-J

Is there a way to prevent this encoding from happening?

Thanks

**Comment by MadAnd** [comment]
Hi @JohnMcAvinue ,
while maintainer not merged my pull request, you can download [SimpleAjaxUploader.js](https://raw.githubusercontent.com/MadAnd/Simple-Ajax-Uploader/master/SimpleAjaxUploader.js) from my [fork](https://github.com/MadAnd/Simple-Ajax-Uploader):

```javascript
var uploader = new ss.SimpleUpload({
      button: 'upload-btn',
      url: '/PathTo/UploadHandler',
      name: 'uploadfile',
      // add the following new option:
      encodeCustomHeaders: false
});
```

Please note, that only the main un-minified file (SimpleAjaxUploader.js) is patched, while SimpleAjaxUploader.min.js - is not!

**Comment by JohnMcAvinue** [comment]
Thanks very much. I ended up removing the encoding myself but it's obviously better to have it based on a setting. I appreciate you sharing it, thanks!
