### ISSUE TITLE
Button in an overflow

### ISSUE THREAD

**Issue by NaWer** [LPology/Simple-Ajax-Uploader#94]
form is in an absolute position relative to the body, so the HTML element used as upload button can't be hidden in an element with scrollbar (mouseover event is not triggered ?) :
https://jsfiddle.net/Lxc92mty/3/

(chrome 41)

**Comment by nickgardos** [comment]
I have the exact same problem

**Comment by LPology** [comment]
The new `updatePosition()` method will fix this:

https://jsfiddle.net/14abx1yj/2/

**Comment by LPology** [comment]
Upgrading to version 2.2, released yesterday, may fix this. I forked that jsfiddle and updated with version 2.2 of the plugin, and the issue no longer exists.

https://jsfiddle.net/gkfdj3et/1/
