### ISSUE TITLE
Upload images using script

### ISSUE THREAD

**Issue by ksos** [LPology/Simple-Ajax-Uploader#97]
Hi all,

first of all thanks for all contributors.

I am trying to automatize the upload using a script (CasperJS).
Normally i use this code to upload file : 
this.page.uploadFile('input[type="file"]', fileName);

but it does not work here.
do you have any clue about how can i do that?

thank you

**Comment by LPology** [comment]
Sorry for the long delay in responding. I am not familiar with CasperJS.
