### ISSUE TITLE
something went wrong when i tried to upload some  files

### ISSUE THREAD

**Issue by jonny77** [LPology/Simple-Ajax-Uploader#99]
when i use the sub code:
var uploader = new ss.SimpleUpload({
			  button: 'uploadBtn', // HTML element used as upload button
			  url: '/api/upload/image', // URL of server-side upload handler
			  name: 'image', // Parameter name of the uploaded file
			  data:{token:'<?php echo $upload_token?>'},
			  method:'post'
		});
i got nothing with:
print_r($_FILES);
is there anything wrong?

**Comment by DanielFris** [comment]
Perhaps - Your url: should be leading to a server side handler file ( not an upload directory ).
